#!/usr/bin/env python3
"""Generate the fail-closed local EXP-STOP-001 status table and manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import tempfile

from stopping_local_evidence import (
    ANALYSIS_NAME,
    MANIFEST_NAME,
    PLAN_NAME,
    TABLE_NAME,
    audit_campaign,
    render_table,
    sha256_file,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_DIR = REPO_ROOT / "paper/tables/generated"
MANIFEST_SCHEMA_ID = "fenics-nonlinear-energies.exp-stop-001-local-table-manifest"
MANIFEST_SCHEMA_VERSION = 1


def _repo_relative(path: Path, *, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError as exc:
        raise ValueError(f"path must remain inside the repository: {path}") from exc


def _atomic_bytes(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(data)
        handle.flush()
    temporary.replace(path)


def _atomic_json(path: Path, payload: object) -> None:
    _atomic_bytes(
        path,
        (json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n").encode(
            "utf-8"
        ),
    )


def build_manifest(
    *,
    evidence_root: Path,
    audit: dict[str, object],
    table_sha256: str,
    repo_root: Path = REPO_ROOT,
) -> dict[str, object]:
    paths = {
        "validator": repo_root / "paper/scripts/stopping_local_evidence.py",
        "generator": repo_root / "paper/scripts/generate_stopping_local_status.py",
        "checker": repo_root / "paper/scripts/check_stopping_local_manifest.py",
    }
    return {
        "schema_id": MANIFEST_SCHEMA_ID,
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "status": "admitted_local_calibration_cluster_deferred",
        "publication_evidence": True,
        "experiment_id": "EXP-STOP-001",
        "evidence_root": _repo_relative(evidence_root, repo_root=repo_root),
        "source_plan": {
            "path": _repo_relative(evidence_root / PLAN_NAME, repo_root=repo_root),
            "sha256": sha256_file(evidence_root / PLAN_NAME),
        },
        "source_analysis": {
            "path": _repo_relative(evidence_root / ANALYSIS_NAME, repo_root=repo_root),
            "sha256": sha256_file(evidence_root / ANALYSIS_NAME),
        },
        "source_commit": audit["source_commit"],
        "audit": audit,
        "tools": {
            key: {
                "path": _repo_relative(path, repo_root=repo_root),
                "sha256": sha256_file(path),
            }
            for key, path in paths.items()
        },
        "outputs": {TABLE_NAME: table_sha256},
        "complete_exp_stop_pass": False,
        "timing_claim_admissible": False,
        "population_robustness_claim_admissible": False,
        "allow_unreferenced_tables": True,
    }


def generate(
    evidence_root: Path,
    out_dir: Path,
    *,
    repo_root: Path = REPO_ROOT,
    require_release_clean: bool = True,
) -> dict[str, object]:
    evidence_root = evidence_root.expanduser()
    if not evidence_root.is_absolute():
        evidence_root = repo_root / evidence_root
    evidence_root = evidence_root.absolute()
    audit = audit_campaign(
        evidence_root,
        repo_root=repo_root,
        require_release_clean=require_release_clean,
    )
    table = render_table(audit).encode("utf-8")
    table_hash = hashlib.sha256(table).hexdigest()
    manifest = build_manifest(
        evidence_root=evidence_root,
        audit=audit,
        table_sha256=table_hash,
        repo_root=repo_root,
    )
    table_path = out_dir / TABLE_NAME
    _atomic_bytes(table_path, table)
    if sha256_file(table_path) != table_hash:
        raise OSError("written stopping status table differs from generated bytes")
    _atomic_json(out_dir / MANIFEST_NAME, manifest)
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-root", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args(argv)
    try:
        manifest = generate(args.evidence_root, args.out_dir)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    print(json.dumps(manifest, indent=2, sort_keys=True, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
