#!/usr/bin/env python3
"""Generate the correctness-only distributed colored-recovery paper table."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import tempfile

from distributed_colored_evidence import (
    MANIFEST_NAME,
    TABLE_NAME,
    audit_campaign,
    render_table,
    sha256_file,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_DIR = REPO_ROOT / "paper/tables/generated"
MANIFEST_SCHEMA_ID = "fenics-nonlinear-energies.distributed-colored-table-manifest"
MANIFEST_SCHEMA_VERSION = 1


def _repo_relative(path: Path, *, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError as exc:
        raise ValueError(f"path must remain inside the repository: {path}") from exc


def _write_bytes_atomic(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(data)
        handle.flush()
    temporary.replace(path)


def _write_json_atomic(path: Path, value: object) -> None:
    data = (json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n").encode(
        "utf-8"
    )
    _write_bytes_atomic(path, data)


def build_manifest(
    *,
    evidence_root: Path,
    audit: dict[str, object],
    table_sha256: str,
    repo_root: Path = REPO_ROOT,
) -> dict[str, object]:
    evidence_root = evidence_root.resolve()
    source_manifest = evidence_root / "manifest.json"
    validator = repo_root / "paper/scripts/distributed_colored_evidence.py"
    generator = repo_root / "paper/scripts/generate_distributed_colored_table.py"
    checker = repo_root / "paper/scripts/check_distributed_colored_manifest.py"
    tools = {
        "validator": {
            "path": _repo_relative(validator, repo_root=repo_root),
            "sha256": sha256_file(validator),
        },
        "generator": {
            "path": _repo_relative(generator, repo_root=repo_root),
            "sha256": sha256_file(generator),
        },
        "checker": {
            "path": _repo_relative(checker, repo_root=repo_root),
            "sha256": sha256_file(checker),
        },
    }
    return {
        "schema_id": MANIFEST_SCHEMA_ID,
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "status": "admitted_correctness_only",
        "publication_evidence": True,
        "experiment_id": "EXP-DIST-001",
        "evidence_root": _repo_relative(evidence_root, repo_root=repo_root),
        "source_campaign_manifest": {
            "path": _repo_relative(source_manifest, repo_root=repo_root),
            "sha256": sha256_file(source_manifest),
        },
        "source_commit": audit["source_commit"],
        "audit": audit,
        "tools": tools,
        "outputs": {TABLE_NAME: table_sha256},
        "timing_claim_admissible": False,
        "allow_unreferenced_tables": True,
    }


def generate(
    evidence_root: Path,
    out_dir: Path,
    *,
    repo_root: Path = REPO_ROOT,
) -> dict[str, object]:
    evidence_root = evidence_root.expanduser()
    if not evidence_root.is_absolute():
        evidence_root = repo_root / evidence_root
    evidence_root = evidence_root.resolve()
    audit = audit_campaign(evidence_root, repo_root=repo_root)
    table = render_table(audit).encode("utf-8")
    table_sha256 = hashlib.sha256(table).hexdigest()
    manifest = build_manifest(
        evidence_root=evidence_root,
        audit=audit,
        table_sha256=table_sha256,
        repo_root=repo_root,
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    table_path = out_dir / TABLE_NAME
    _write_bytes_atomic(table_path, table)
    if sha256_file(table_path) != table_sha256:
        raise OSError("written distributed-colored table differs from the generated bytes")
    _write_json_atomic(out_dir / MANIFEST_NAME, manifest)
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-root", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args(argv)
    try:
        manifest = generate(args.evidence_root, args.out_dir)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    print(json.dumps(manifest, indent=2, sort_keys=True, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
