"""Support utilities for the experimental slope-stability family."""

from src.problems.slope_stability.support.mesh import (
    DEFAULT_CASE,
    DEFAULT_LEVEL,
    LEGACY_DEFAULT_CASE,
    SlopeStabilityCaseData,
    build_elastic_initial_guess,
    build_case_data,
    build_near_nullspace_modes,
    build_refined_p1_case_data,
    build_same_mesh_lagrange_case_data,
    build_scalar_mesh_counts,
    canonical_case_name,
    case_name_for_level,
    ensure_same_mesh_case_hdf5,
    ensure_all_level_case_hdf5,
    ensure_level_case_hdf5,
    h_for_level,
    level_case_hdf5_path,
    level_for_case_name,
    load_case_hdf5,
    load_case_hdf5_fields,
    load_same_mesh_case_hdf5_light,
    load_same_mesh_case_hdf5_rank_local,
    same_mesh_case_hdf5_path,
    same_mesh_case_name,
    supported_levels,
    write_case_hdf5,
)
from src.problems.slope_stability.support.reduction import davis_b_reduction

__all__ = [
    "DEFAULT_CASE",
    "DEFAULT_LEVEL",
    "LEGACY_DEFAULT_CASE",
    "SlopeStabilityCaseData",
    "build_elastic_initial_guess",
    "build_case_data",
    "build_near_nullspace_modes",
    "build_refined_p1_case_data",
    "build_same_mesh_lagrange_case_data",
    "build_scalar_mesh_counts",
    "canonical_case_name",
    "case_name_for_level",
    "davis_b_reduction",
    "ensure_all_level_case_hdf5",
    "ensure_level_case_hdf5",
    "ensure_same_mesh_case_hdf5",
    "h_for_level",
    "level_case_hdf5_path",
    "level_for_case_name",
    "load_case_hdf5",
    "load_case_hdf5_fields",
    "load_same_mesh_case_hdf5_light",
    "load_same_mesh_case_hdf5_rank_local",
    "same_mesh_case_hdf5_path",
    "same_mesh_case_name",
    "supported_levels",
    "write_case_hdf5",
]
